# Nom affiché dans l'onglet "Actions" de Github

name: Déploiement (version B - SSH)

# QUAND le workflow se lance
on:
  # à chaque envoie de code (git push)...     
  push:
    # ... mais seulement sur la branche main
    branches: [main]
    
    # CE QU'IL FAIT : une liste de "jobs" (groupe de tâches)
    # Job : un groupe de tâches exécutées sur un même runner, les unes après les autres
jobs:
    # Nom de notre unique job (choisi librement)
  deploy:
    # Le runner : un Ubuntu temporaire prêté par Github
    runs-on: ubuntu-latest
    # Donne accès aux secrets et variables de l'environnement "vps"
    environment: vps
    # Variables données au runner pour tout le job
    env:
      # Adresse du serveur, lue dans les secrets de "vps"
      VPS_HOST: ${{ secrets.VPS_HOST }}
      # Compte sur le serveur
      VPS_USER: ${{ secrets.VPS_USER }}
      # Mot de passe : 
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      # Dossier du projet sur le serveur, lu dans les variables "vps"
      APP_PATH: ${{ vars.APP_PATH }}
      # Clés d'hôte du serveur, pour vérifier son identité
      VPS_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}


    # La liste des étapes, exécutées dans l'ordre
    steps:
      # Étape 1 : copier le code du dépôt dans le runner
      - name: Récupérer le code
        # Action officielle de Github, version majeure 6
        uses: actions/checkout@v6

      # Étape 2 : écrire la clé privée dans un fichier du runner - seul le proprio peut lire la clé
      - name: Préparer la clé SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$VPS_SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          printf '%s\n' "$VPS_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Étape 3 : copier le code du runner vers le serveur
      - name: Copier le code sur le serveur
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.env' \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./ "$VPS_USER@$VPS_HOST:$APP_PATH/"

      # Étape 4 : se connecter au serveur et relancer les conteneurs
      - name: Relancer les conteneurs sur le serveur
        run: |
          ssh -i ~/.ssh/deploy_key "$VPS_USER@$VPS_HOST" << EOF
            cd $APP_PATH
            docker compose up -d --build
          EOF

